services:
  planner-admin:
    image: planner-admin:latest
    ports:
      - "3000:80"
    environment:
      PLANNER_API_URL: "http://localhost:8080"
    restart: unless-stopped
    networks:
      - planner-network

networks:
  planner-network:
    external: true