services:
  planner-admin:
    image: ${DOCKER_USERNAME}/planner-admin:${TAG}
    container_name: planner-admin
    restart: always
    environment:
      TZ: Europe/Moscow
      PLANNER_API_URL: ${PLANNER_API_URL}
    ports:
      - "8091:80"
    env_file:
      - .env
    networks:
      - planner-network

networks:
  planner-network:
    external: true